blank_issues_enabled: false
contact_links:
  - name: support forum
    url: https://github.com/Muppetsg2/koi/discussions/categories/q-a
    about: having trouble using an koi library? don't create an issue, post in the forum
